version: '2'

services:
  flask-erp:
    container_name: container-flask-erp
    build: .
    image: image-flask-erp
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      mysqlsrv:
        condition: service_healthy
    env_file:
      - .env
    networks:
      network:
        ipv4_address: "172.20.0.2"


  mysqlsrv:
    image: "mysql:5.7"
    command: --default-authentication-plugin=mysql_native_password
    container_name: container-mysqlsrv
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fast_lunch_db
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=user_app
      - MYSQL_PASSWORD=pass_user_app
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      network:
        ipv4_address: "172.20.0.3"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"USE fast_lunch_db;\""
      timeout: 10s
      retries: 10
  
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16